# Parameters are described by its name, value, and range.
# All three items separated by commas

# Default PARAMETERS

# Morphological element used for binary operations, e.g. opening, closing, etc.
element_size = 5
element_size_range = [3, 10]

# Connectivity used, use 4 or 8
connectivity = 8
connectivity_range = [4, 8]

# Marker size for watershed segmentation
Marker_size = 10
Marker_size_range = [2, 30]

# Images can be resampled to make processing faster
resample = 0.5
resample_range = [0.1, 1.0]

# Reject abnormal bubbles from quantification. E>0.85 or S<0.9
max_eccentricity = 0.85
max_eccentricity_range = [0.1, 1.0]
min_solidity = 0.9
min_solidity_range = [0.1, 1.0]


# Also ignore too small bubbles (equivalent diameter in mm)
min_size = 0.1
min_size_range = [0, 50]

# Image resolution
px2mm = 1.0

# Target image
raw_img_path = "."

# Background image
bknd_img_path = "None"

# Ruler image
ruler_img_path = "."

# Save path
save_path = "."

# Save path for Images
save_path_for_images = "."

# Threshold value for background subtraction
threshold_value = 0.3

# Batch processing flag
do_batch = false

# Img resample factors
img_resample = 0.5

# Default setting values for iterative methods
max_thresh = 0.95
min_thresh = 0.05
step_size = 0.05
