name: Test and build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.12.3"]

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.8.4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: poetry

      - name: Show Python Version
        run: python --version

      - name: Install dependencies
        run: poetry install

      - name: Debug Poetry Environment
        run: poetry env list

      - name: Run tests
        run: poetry run pytest
